export const NAVIGATE_URL = {
  FORBIDDEN: '/403',
  USERS: '/users',
  USER_UPDATE: '/users/update',
  USER_CREATE: '/users/create',
  USER_MANAGEMENT: '/user-management',
  PROJECT_MANAGEMENT: '/project-management',
  PROFILE_UPDATE: '/profile/update',
  CHANGE_PASSWORD: '/profile/change-password',
  SIGN_IN: '/sign-in',
  SIGN_OUT: '/sign-out',
  PROFILE: '/profile',
  ELECTRICITY_SETTING_PRICE: '/price-settings/electricity-price',
  WATER_SETTING_PRICE: '/price-settings/water-price',
};
