export const QUERY_KEY = {
  RBAC: 'RBAC',
  PERMISSIONS: 'PERMISSIONS',
  ROLES: 'ROLES',
  USERS: 'USERS',
  PROFILE: 'PROFILE',
  DEVICES: 'DEVICES',
  DEVICES_SUMMARIZE: 'DEVICES_SUMMARIZE',
  DEVICE_TELEMETRY_KEYS: 'DEVICE_TELEMETRY_KEYS',
  CARDS_OPEN: 'CARDS_OPEN',
  HISTORY_REGISTRIES: 'HISTORY_REGISTRIES',
  MAINTENANCES: 'MAINTENANCES',
  SESSIONS: 'SESSIONS',
  SESSIONS_SUGGEST_POINT: 'SESSIONS_SUGGEST_POINT',
  SESSIONS_EMULATOR: 'SESSIONS_EMULATOR',
  SESSIONS_ROUTE: 'SESSIONS_ROUTE',
  SESSIONS_LOCATIONS: 'SESSIONS_LOCATIONS',
  STUDENT_SESSIONS: 'STUDENT_SESSIONS',
  HAPPENING_SESSIONS: 'HAPPENING_SESSIONS',
  PARAMETER_CONFIGURATION: 'PARAMETER_CONFIGURATION',
  FIRST_REPORTS: 'FIRST_REPORTS',
  DATA_CARD: 'DATA_CARD',
  DATA_CHART: 'DATA_CHART',
  CABINS: 'CABINS',
  PROJECT: 'PROJECT',
  ELECTRICITY_CONSUMPTION: 'ELECTRICITY_CONSUMPTION',
  DETAIL_DEVICE: 'DETAIL_DEVICE',
  LOCATION_TYPES: 'LOCATION_TYPES',
  LOCATIONS: 'LOCATIONS',
  METER_TYPES: 'METER_TYPES',
  DEVICE_BY_IDS: 'DEVICE_BY_IDS',
  UNASSIGNED_DEVICES: 'UNASSIGNED_DEVICES',
};

export const REACT_QUERY = {
  REQUEST_CACHE_TIME: 10 * 60 * 1000, // 10m
  REQUEST_STALE_TIME: 10 * 60 * 1000, // 10m
};

export const REQUEST_DEBOUNCE_DEFAULT_TIME = 1000;
