export const QUERY_KEY = {
  RBAC: 'RBAC',
  PERMISSIONS: 'PERMISSIONS',
  ROLES: 'ROLES',
  USERS: 'USERS',
  PROFILE: 'PROFILE',
  DEVICES: 'DEVICES',
  CARDS_OPEN: 'CARDS_OPEN',
  HISTORY_REGISTRIES: 'HISTORY_REGISTRIES',
  MAINTENANCES: 'MAINTENANCES',
  SESSIONS: 'SESSIONS',
  SESSIONS_SUGGEST_POINT: 'SESSIONS_SUGGEST_POINT',
  SESSIONS_EMULATOR: 'SESSIONS_EMULATOR',
  SESSIONS_ROUTE: 'SESSIONS_ROUTE',
  SESSIONS_LOCATIONS: 'SESSIONS_LOCATIONS',
  STUDENT_SESSIONS: 'STUDENT_SESSIONS',
  HAPPENING_SESSIONS: 'HAPPENING_SESSIONS',
  PARAMETER_CONFIGURATION: 'PARAMETER_CONFIGURATION',
  FIRST_REPORTS: 'FIRST_REPORTS',
  DATA_CARD: 'DATA_CARD',
  DATA_CHART: 'DATA_CHART',
  CABINS: 'CABINS',
  LOCATION_TYPE: 'LOCATION_TYPE',
  PRICING_ELECTRIC_RULE: 'PRICING_ELECTRIC_RULE',
};

export const REACT_QUERY = {
  REQUEST_CACHE_TIME: 10 * 60 * 1000, // 10m
  REQUEST_STALE_TIME: 10 * 60 * 1000, // 10m
};

export const REQUEST_DEBOUNCE_DEFAULT_TIME = 1000;
